
name: Release

on:
  push:
    tags:
    - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Git fetch tags
      run: "git fetch --tags"
    
    - name: Find latest tag
      id: latest-tag
      run: |
        echo "LATEST_TAG=$(git tag --sort=-version:refname | head -n 1)" >> $GITHUB_OUTPUT
        echo "SECOND_LATEST_TAG=$(git tag --sort=-version:refname | head -n 2 | tail -n 1)" >> $GITHUB_OUTPUT

    - name: Get changelog
      id: changelog
      run: |
        git log --oneline "${{ steps.latest-tag.outputs.SECOND_LATEST_TAG }}..HEAD" \
          | cut -d " " -f2- | grep -vE '^Merge pull request' | sed -e 's/^/ - /' >release.md
        cat release.md
    
    - name: Checkout latest tag
      run: "git checkout tags/${{ steps.latest-tag.outputs.LATEST_TAG }}"

    - name: Set up Go
      uses: "actions/setup-go@v3"
      with:
        go-version: 1.18
    
    - name: Clean
      run: "make clean"

    - name: Build
      run: "make build-all"
    
    - name: Create Release
      uses: "ncipollo/release-action@v1"
      with:
        artifacts: "build/*"
        bodyFile: "release.md"
        tag: "${{ steps.latest-tag.outputs.LATEST_TAG }}"
