
name: Release

on:
  push:
    tags:
    - v*

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Git fetch
      run: "git fetch --tags"
    
    - name: Find latest tag
      id: latest-tag
      run: |
        echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
    
    - name: Checkout latest tag
      run: "git checkout tags/${{ steps.latest-tag.outputs.LATEST_TAG }}"

    - name: Set up Go
      uses: "actions/setup-go@v3"
      with:
        go-version: 1.18
    
    - name: Clean
      run: "make clean"

    - name: Build
      run: "make build-all"
    
    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ steps.latest-tag.outputs.LATEST_TAG }}"
        prerelease: false
        title: "${{ steps.latest-tag.outputs.LATEST_TAG }}"
        files: |
          build/*
